// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

namespace Richasy.BiliKernel.Services.Media.Core.Models;

internal sealed class ArchiveRelationResponse
{
    public bool attention { get; set; }
    public bool favorite { get; set; }
    public bool season_fav { get; set; }
    public bool like { get; set; }
    public bool dislike { get; set; }
    public int coin { get; set; }
}
