// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

namespace Richasy.BiliKernel.Services.Media.Core.Models;

internal sealed class EnterRoomMessage
{
    public int roomid { get; set; }
    public long uid { get; set; }
    public string buvid { get; set; }
    public int protover { get; set; }
    public string key { get; set; }
}
