// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

namespace Richasy.BiliKernel.Services.Media.Core.Models;

internal sealed class PlayerWbiResponse
{
    public long aid { get; set; }
    public string bvid { get; set; }
    public long cid { get; set; }
    public bool is_owner { get; set; }
    public int last_play_time { get; set; }
    public long last_play_cid { get; set; }
    public int online_count { get; set; }
}
