// Copyright (c) Richasy. All rights reserved.

using System.Collections.Generic;
using System.Text.Json.Serialization;
using Richasy.BiliKernel.Content;
using Richasy.BiliKernel.Services.User.Core;
using Richasy.BiliKernel.Services.User.Core.Models;

namespace Richasy.BiliKernel.Services.User;

[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(ArticleFavoriteListResponse))]
[JsonSerializable(typeof(FavoriteArticleItem))]
[JsonSerializable(typeof(AtMessageResponse))]
[JsonSerializable(typeof(AtMessageItem))]
[JsonSerializable(typeof(AtMessageResponse))]
[JsonSerializable(typeof(AtMessageItemDetail))]
[JsonSerializable(typeof(BiliChatUser))]
[JsonSerializable(typeof(ChatSessionListResponse))]
[JsonSerializable(typeof(ChatMessageResponse))]
[JsonSerializable(typeof(SendMessageResponse))]
[JsonSerializable(typeof(ChatEmoteInfo))]
[JsonSerializable(typeof(BiliChatSession))]
[JsonSerializable(typeof(BiliChatMsg))]
[JsonSerializable(typeof(FavoriteDetailListResponse))]
[JsonSerializable(typeof(FavoriteMeta))]
[JsonSerializable(typeof(FavoriteListResponse))]
[JsonSerializable(typeof(LikeMessageResponse))]
[JsonSerializable(typeof(LikeMesageLatest))]
[JsonSerializable(typeof(LikeMessageItem))]
[JsonSerializable(typeof(LikeMessageItemDetail))]
[JsonSerializable(typeof(LikeMessageTotal))]
[JsonSerializable(typeof(MessageCursor))]
[JsonSerializable(typeof(MessageUser))]
[JsonSerializable(typeof(MessageItem))]
[JsonSerializable(typeof(MessageItemDetail))]
[JsonSerializable(typeof(Mine))]
[JsonSerializable(typeof(MyInfo))]
[JsonSerializable(typeof(Vip))]
[JsonSerializable(typeof(PgcFavoriteListResponse))]
[JsonSerializable(typeof(PgcArea))]
[JsonSerializable(typeof(FavoritePgcItem))]
[JsonSerializable(typeof(PgcProgress))]
[JsonSerializable(typeof(PgcSeries))]
[JsonSerializable(typeof(PgcEpisode))]
[JsonSerializable(typeof(PublisherInfo))]
[JsonSerializable(typeof(RelatedTag))]
[JsonSerializable(typeof(RelatedUser))]
[JsonSerializable(typeof(RelatedUserVip))]
[JsonSerializable(typeof(RelatedUserResponse))]
[JsonSerializable(typeof(ReplyMessageResponse))]
[JsonSerializable(typeof(ReplyMessageItem))]
[JsonSerializable(typeof(ReplyMessageItemDetail))]
[JsonSerializable(typeof(UgcSeasonDetailResponse))]
[JsonSerializable(typeof(UgcSeasonPage))]
[JsonSerializable(typeof(UgcSeasonArchive))]
[JsonSerializable(typeof(UgcSeasonStat))]
[JsonSerializable(typeof(UnreadMessage))]
[JsonSerializable(typeof(UserRelationResponse))]
[JsonSerializable(typeof(VideoFavoriteGalleryResponse))]
[JsonSerializable(typeof(VideoFavoriteListResponse))]
[JsonSerializable(typeof(FavoriteListDetail))]
[JsonSerializable(typeof(FavoriteMedia))]
[JsonSerializable(typeof(FavoriteMediaStat))]
[JsonSerializable(typeof(FavoriteFolder))]
[JsonSerializable(typeof(FavoriteMediaList))]
[JsonSerializable(typeof(VideoStatusInfo))]
[JsonSerializable(typeof(ViewLaterSetResponse))]
[JsonSerializable(typeof(ViewLaterVideo))]
[JsonSerializable(typeof(BiliDataResponse<MyInfo>))]
[JsonSerializable(typeof(BiliDataResponse<Mine>))]
[JsonSerializable(typeof(BiliDataResponse<List<RelatedTag>>))]
[JsonSerializable(typeof(BiliDataResponse<List<RelatedUser>>))]
[JsonSerializable(typeof(BiliDataResponse<RelatedUserResponse>))]
[JsonSerializable(typeof(BiliDataResponse<UserRelationResponse>))]
[JsonSerializable(typeof(BiliDataResponse<UnreadMessage>))]
[JsonSerializable(typeof(BiliDataResponse<ChatMessageResponse>))]
[JsonSerializable(typeof(BiliDataResponse<SendMessageResponse>))]
[JsonSerializable(typeof(BiliDataResponse<ChatSessionListResponse>))]
[JsonSerializable(typeof(BiliDataResponse<List<BiliChatUser>>))]
[JsonSerializable(typeof(BiliDataResponse<LikeMessageResponse>))]
[JsonSerializable(typeof(BiliDataResponse<AtMessageResponse>))]
[JsonSerializable(typeof(BiliDataResponse<ReplyMessageResponse>))]
[JsonSerializable(typeof(BiliDataResponse<VideoFavoriteGalleryResponse>))]
[JsonSerializable(typeof(BiliDataResponse<FavoriteDetailListResponse>))]
[JsonSerializable(typeof(BiliDataResponse<ArticleFavoriteListResponse>))]
[JsonSerializable(typeof(BiliResultResponse<PgcFavoriteListResponse>))]
[JsonSerializable(typeof(BiliDataResponse<FavoriteListResponse>))]
[JsonSerializable(typeof(BiliDataResponse<VideoFavoriteListResponse>))]
[JsonSerializable(typeof(BiliDataResponse<UgcSeasonDetailResponse>))]
[JsonSerializable(typeof(BiliDataResponse<bool>))]
[JsonSerializable(typeof(BiliDataResponse<ViewLaterSetResponse>))]
internal sealed partial class SourceGenerationContext : JsonSerializerContext
{
}
