// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

using System.Collections.Generic;

namespace Richasy.BiliKernel.Services.Search.Core;

internal sealed class SearchPartitionResponse
{
    public int page { get; set; }
    public int pagesize { get; set; }
    public int numResults { get; set; }
    public int numPages { get; set; }
    public string suggest_keyword { get; set; }
    public string rqt_type { get; set; }
    public int egg_hit { get; set; }
    public List<SearchVideo> result { get; set; }
    public int show_column { get; set; }
    public int in_black_key { get; set; }
    public int in_white_key { get; set; }
}

internal sealed class SearchVideo
{
    public string type { get; set; }
    public long id { get; set; }
    public string author { get; set; }
    public long mid { get; set; }
    public string typeid { get; set; }
    public string typename { get; set; }
    public string arcurl { get; set; }
    public long aid { get; set; }
    public string bvid { get; set; }
    public string title { get; set; }
    public string description { get; set; }
    public string pic { get; set; }
    public int play { get; set; }
    public int video_review { get; set; }
    public int favorites { get; set; }
    public int review { get; set; }
    public long pubdate { get; set; }
    public string duration { get; set; }
    public int like { get; set; }
    public string upic { get; set; }
    public string cover { get; set; }
    public string desc { get; set; }
    public string url { get; set; }
    public int danmaku { get; set; }
    public int is_charge_video { get; set; }
    public int vt { get; set; }
    public int enable_vt { get; set; }
    public string subtitle { get; set; }
    public int release_status { get; set; }
    public string cate_name { get; set; }
    public string tags { get; set; }
    public string uface { get; set; }
    public int uid { get; set; }
    public string uname { get; set; }
    public string user_cover { get; set; }
    public int parent_area_id { get; set; }
    public string parent_area_name { get; set; }
}

